spring: 
    profiles: 
      active: 
      - dev
---
spring: 
    profiles: dev
    application: 
        name: provider_dev
---
spring: 
    profiles: test
    application: 
        name: provider_test