spring:
  profiles:
    active:
    - dev
---
server:
  port: 8764
spring:
  profiles: dev
eureka:
  instance:
    hostname: eureka_server_8764
  client:
    #fetch-registry: false
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
